/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LoQuery: typeof import('./src/components/query/query.vue')['default']
    LoQueryItem: typeof import('./src/components/query/queryItem.vue')['default']
    Query: typeof import('./src/components/query/query.vue')['default']
    QueryItem: typeof import('./src/components/query/queryItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
